# Generated by Django 3.0.6 on 2020-07-27 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_friend_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friend_requests',
            field=models.ManyToManyField(related_name='friendrequests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='friend_list',
            field=models.ManyToManyField(related_name='friendlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
