# Generated by Django 3.0.6 on 2020-07-27 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200727_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friend_list',
            field=models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
