# Generated by Django 3.0.6 on 2020-07-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='subject',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='message',
            new_name='content',
        ),
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.CharField(default=models.CharField(max_length=255), max_length=1000),
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='user_account_outdated', unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
