# Generated by Django 3.0.6 on 2020-07-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20200713_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='group_outdated', unique=True),
        ),
    ]
