# Generated by Django 3.0.6 on 2020-07-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20200713_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(default='boardy_mc_boardface', max_length=1000),
        ),
    ]
