# Generated by Django 3.0.6 on 2020-12-31 01:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=uuid.uuid1, max_length=400, unique=True)),
                ('info', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('info', models.CharField(max_length=400)),
                ('desc', models.CharField(max_length=400)),
                ('urls', models.CharField(max_length=400)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Listing')),
            ],
        ),
    ]
