# Generated by Django 3.0.6 on 2020-11-20 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('info', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='course',
            name='info',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='course',
            name='urls',
            field=models.CharField(max_length=400),
        ),
        migrations.AddField(
            model_name='course',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Listing'),
            preserve_default=False,
        ),
    ]
