# Generated by Django 3.0.6 on 2020-12-31 01:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
